<?php
// Generates a blue-themed overview PDF (tables only) using DOMPDF

require '../../vendor/autoload.php'; // Composer autoload
include('../../includes/staff_auth.php');
include('../../db_connect.php');
include('../../includes/path_helper.php');

use Dompdf\Dompdf;
use Dompdf\Options;

// Fetch data (same as reports/index.php)
$totalBooks = (int)($conn->query("SELECT COUNT(*) AS t FROM books")->fetch_assoc()['t'] ?? 0);
$totalMembers = (int)($conn->query("SELECT COUNT(*) AS t FROM members WHERE status='active'")->fetch_assoc()['t'] ?? 0);
$totalBorrowed = (int)($conn->query("SELECT COUNT(*) AS t FROM borrow_records")->fetch_assoc()['t'] ?? 0);
$totalReturned = (int)($conn->query("SELECT COUNT(*) AS t FROM borrow_records WHERE returned_at IS NOT NULL")->fetch_assoc()['t'] ?? 0);
$notReturned = max(0, $totalBorrowed - $totalReturned);

$year = date('Y');
$months = [];
$monthCounts = [];
for ($m = 1; $m <= 12; $m++) {
    $months[] = date('M', mktime(0,0,0,$m,1));
    $start = "$year-" . str_pad($m,2,'0',STR_PAD_LEFT) . "-01 00:00:00";
    $end = date('Y-m-t 23:59:59', strtotime($start));
    $q = $conn->query("SELECT COUNT(*) AS total FROM borrow_records WHERE borrowed_at BETWEEN '$start' AND '$end'");
    $monthCounts[] = (int)($q->fetch_assoc()['total'] ?? 0);
}

// Top 5 books
$topBooks = [];
$tb = $conn->query("
    SELECT b.title, COUNT(*) AS times
    FROM borrow_records br
    JOIN books b ON br.book_id = b.id
    GROUP BY br.book_id
    ORDER BY times DESC
    LIMIT 5
");
while ($r = $tb->fetch_assoc()) {
    $topBooks[] = $r;
}

// Top 5 members
$topMembers = [];
$tm = $conn->query("
    SELECT m.full_name, COUNT(*) AS times
    FROM borrow_records br
    JOIN members m ON br.member_id = m.id
    GROUP BY br.member_id
    ORDER BY times DESC
    LIMIT 5
");
while ($r = $tm->fetch_assoc()) {
    $topMembers[] = $r;
}

// Prepare HTML for PDF
$logo_path = realpath(__DIR__ . '/../../assets/img/cuulogo.png'); // absolute path for dompdf
$logo_html = '';
if ($logo_path && file_exists($logo_path)) {
    // Use file:// protocol so dompdf can read local file
    $logo_html = '<img src="file://' . $logo_path . '" style="height:60px; margin-right:12px;">';
}

$generated_at = date('Y-m-d H:i');

$html = '
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Library Overview Report</title>
<style>
    body { font-family: DejaVu Sans, Helvetica, Arial, sans-serif; color:#222; }
    .header { display:flex; align-items:center; border-bottom:3px solid #033B5C; padding-bottom:10px; margin-bottom:12px; }
    .title { color:#033B5C; font-size:20px; font-weight:700; }
    .meta { font-size:12px; color:#444; margin-left:auto; text-align:right; }
    .section { margin-top:16px; }
    .card-grid { width:100%; display:flex; gap:10px; margin-bottom:10px; }
    .card { background:#f6fbff; border:1px solid #e6f0f7; padding:10px; border-radius:6px; flex:1; }
    .card .label { color:#05506f; font-weight:700; font-size:12px; }
    .card .val { color:#033B5C; font-size:18px; font-weight:700; margin-top:6px; }

    table { width:100%; border-collapse:collapse; margin-top:8px; }
    table th, table td { border:1px solid #e1eef7; padding:8px; font-size:12px; }
    table th { background:#f0f9ff; color:#033B5C; text-align:left; }
    .small { font-size:11px; color:#666; }

    .footer-note { margin-top:18px; font-size:11px; color:#666; }
</style>
</head>
<body>
<div class="header">
    ' . $logo_html . '
    <div>
        <div class="title">Cavendish Library — Overview Report</div>
        <div class="small">Year: ' . $year . '</div>
    </div>
    <div class="meta">
        Generated: ' . htmlspecialchars($generated_at) . '<br>
        Generated by: ' . htmlspecialchars($_SESSION['username']) . '
    </div>
</div>

<div class="section">
    <div class="card-grid">
        <div class="card"><div class="label">Total Books</div><div class="val">' . number_format($totalBooks) . '</div></div>
        <div class="card"><div class="label">Total Members (active)</div><div class="val">' . number_format($totalMembers) . '</div></div>
        <div class="card"><div class="label">Total Borrowed (all-time)</div><div class="val">' . number_format($totalBorrowed) . '</div></div>
        <div class="card"><div class="label">Currently Borrowed</div><div class="val">' . number_format($notReturned) . '</div></div>
    </div>
</div>

<div class="section">
    <h4 style="margin:6px 0; color:#033B5C;">Monthly Borrowing (' . $year . ')</h4>
    <table>
        <thead>
            <tr><th>Month</th><th>Borrows</th></tr>
        </thead>
        <tbody>';
foreach ($months as $i => $m) {
    $html .= '<tr><td>' . htmlspecialchars($m) . '</td><td>' . number_format($monthCounts[$i]) . '</td></tr>';
}
$html .= '
        </tbody>
    </table>
</div>

<div class="section">
    <h4 style="margin:6px 0; color:#033B5C;">Top 5 Most Borrowed Books</h4>
    <table>
        <thead><tr><th>Title</th><th>Times Borrowed</th></tr></thead>
        <tbody>';
if (count($topBooks) === 0) {
    $html .= '<tr><td colspan="2" class="small">No data</td></tr>';
} else {
    foreach ($topBooks as $b) {
        $html .= '<tr><td>' . htmlspecialchars($b['title']) . '</td><td>' . number_format($b['times']) . '</td></tr>';
    }
}
$html .= '
        </tbody>
    </table>
</div>

<div class="section">
    <h4 style="margin:6px 0; color:#033B5C;">Top 5 Most Active Members</h4>
    <table>
        <thead><tr><th>Member</th><th>Borrows</th></tr></thead>
        <tbody>';
if (count($topMembers) === 0) {
    $html .= '<tr><td colspan="2" class="small">No data</td></tr>';
} else {
    foreach ($topMembers as $m) {
        $html .= '<tr><td>' . htmlspecialchars($m['full_name']) . '</td><td>' . number_format($m['times']) . '</td></tr>';
    }
}
$html .= '
        </tbody>
    </table>
</div>

<div class="footer-note">
    Generated by Cavendish Library System — DanielApps.
</div>

</body>
</html>
';

// Configure DOMPDF
$options = new Options();
$options->set('isRemoteEnabled', true); // allow local file:// images
$options->set('isHtml5ParserEnabled', true);
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);

// Paper settings
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// Stream to browser
$filename = "Library_Overview_Report_{$year}.pdf";
$dompdf->stream($filename, ['Attachment' => 1]);
exit;
